### ISSUE TITLE
[GUI] Drop down has default values selected

### ISSUE THREAD

**Issue by Nahrain1** [amosproj/amos2024ss07-updating-flash-boot-loader#140]
## User story
1. As a user, 
2. I want the drop-down menus to have default values pre-selected,
3. So that I can quickly proceed with common actions without having to select the options everytime 

## Acceptance criteria
* Each drop-down menu in the GUI has a sensible default value pre-selected
* The default values have to be commonly used by most users
* Users can still change the selection if the default value is not what they need

## Definition of done (DoD)
- Code review has been completed
- Code has been merged
- Feature branch has been deleted
- Update method signatures in architecture diagram
- MCU & GUI build after merge

**Comment by sebas-rodri** [comment]
TO CAN and 500K
