### ISSUE TITLE
Align on a GUI framework

### ISSUE THREAD

**Issue by wlklsn** [amosproj/amos2024ss07-updating-flash-boot-loader#4]
ideally in c++, so that we can keep the project as consistent as possible.

**Comment by MikeFAU** [comment]
Avalonia UI could be one possibility, since it is open source UI framework. Check out https://avaloniaui.net/

**Comment by sebas-rodri** [comment]
I think a really good option would be the [Qt Framework](https://www.qt.io/product/framework) .
But the L(GPL) License could be a problem.

![Image](https://github.com/amosproj/amos2024ss07-updating-flash-boot-loader/assets/128830580/1a2c685a-5fa8-429e-a985-9d3c82987bda)

I think we should decide if we ask Mr. Demir or rather directly stick to a MIT License. 
Also I think no one in the team has a prefence for any specific Framework so if we stay with the MIT License @MikeFAU option would be probally good.

**Comment by wiklam** [comment]
If we are not going to use QT, just wanted to mark that the Avalonia UI is in C#, there is an alternative option in C [lvgl](https://lvgl.io/).

**Comment by MikeFAU** [comment]
I think we should discuss and align in our team meeting. It also depends on who is mainly working on the SW for the GUI.
